name: client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.15.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.2
  dio: ^5.7.0
  web_socket_channel: ^3.0.1
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  flame_audio: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
